services:
  ascent-lab-blog-frontend:
    image: ascent-lab-blog-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_UID=1000
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081